
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsentimientoServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsentimientoServiceWs {


    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Consentimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConsentimientos", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientos")
    @ResponseWrapper(localName = "obtenerConsentimientosResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientosResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientosRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientosResponse")
    public List<Consentimiento> obtenerConsentimientos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Consentimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPorIdConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerPorIdConcepto")
    @ResponseWrapper(localName = "obtenerPorIdConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerPorIdConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerPorIdConceptoRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerPorIdConceptoResponse")
    public List<Consentimiento> obtenerPorIdConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarConsentimiento", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarConsentimiento")
    @ResponseWrapper(localName = "registrarConsentimientoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarConsentimientoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/registrarConsentimientoRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/registrarConsentimientoResponse")
    public void registrarConsentimiento(
        @WebParam(name = "arg0", targetNamespace = "")
        Consentimiento arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarConsentimiento", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarConsentimiento")
    @ResponseWrapper(localName = "eliminarConsentimientoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarConsentimientoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/eliminarConsentimientoRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/eliminarConsentimientoResponse")
    public void eliminarConsentimiento(
        @WebParam(name = "arg0", targetNamespace = "")
        Consentimiento arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modificarConsentimiento", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ModificarConsentimiento")
    @ResponseWrapper(localName = "modificarConsentimientoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ModificarConsentimientoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/modificarConsentimientoRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/modificarConsentimientoResponse")
    public void modificarConsentimiento(
        @WebParam(name = "arg0", targetNamespace = "")
        Consentimiento arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.Consentimiento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConsentimientoPorId", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientoPorId")
    @ResponseWrapper(localName = "obtenerConsentimientoPorIdResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientoPorIdResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientoPorIdRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientoPorIdResponse")
    public Consentimiento obtenerConsentimientoPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.Consentimiento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConsentimientoPorNombre", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientoPorNombre")
    @ResponseWrapper(localName = "obtenerConsentimientoPorNombreResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerConsentimientoPorNombreResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientoPorNombreRequest", output = "http://servicio.sga.gm.com.mx/ConsentimientoServiceWs/obtenerConsentimientoPorNombreResponse")
    public Consentimiento obtenerConsentimientoPorNombre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
