
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsentimientoServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://201.116.155.166:9999/ConsentimientoServiceImplService/ConsentimientoServiceImpl?wsdl")
public class ConsentimientoServiceImplService
    extends Service
{

    private final static URL CONSENTIMIENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSENTIMIENTOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CONSENTIMIENTOSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.116.155.166:9999/ConsentimientoServiceImplService/ConsentimientoServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSENTIMIENTOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CONSENTIMIENTOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ConsentimientoServiceImplService() {
        super(__getWsdlLocation(), CONSENTIMIENTOSERVICEIMPLSERVICE_QNAME);
    }

    public ConsentimientoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSENTIMIENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsentimientoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CONSENTIMIENTOSERVICEIMPLSERVICE_QNAME);
    }

    public ConsentimientoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSENTIMIENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsentimientoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsentimientoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsentimientoServiceWs
     */
    @WebEndpoint(name = "ConsentimientoServiceImplPort")
    public ConsentimientoServiceWs getConsentimientoServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoServiceImplPort"), ConsentimientoServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsentimientoServiceWs
     */
    @WebEndpoint(name = "ConsentimientoServiceImplPort")
    public ConsentimientoServiceWs getConsentimientoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoServiceImplPort"), ConsentimientoServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSENTIMIENTOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CONSENTIMIENTOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CONSENTIMIENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
