
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsentimientoConceptoServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://201.116.155.166:9999/ConsentimientoConceptoServiceImplService/ConsentimientoConceptoServiceImpl?wsdl")
public class ConsentimientoConceptoServiceImplService
    extends Service
{

    private final static URL CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoConceptoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.116.155.166:9999/ConsentimientoConceptoServiceImplService/ConsentimientoConceptoServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ConsentimientoConceptoServiceImplService() {
        super(__getWsdlLocation(), CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_QNAME);
    }

    public ConsentimientoConceptoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsentimientoConceptoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_QNAME);
    }

    public ConsentimientoConceptoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConsentimientoConceptoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsentimientoConceptoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsentimientoConceptoServiceWs
     */
    @WebEndpoint(name = "ConsentimientoConceptoServiceImplPort")
    public ConsentimientoConceptoServiceWs getConsentimientoConceptoServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoConceptoServiceImplPort"), ConsentimientoConceptoServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsentimientoConceptoServiceWs
     */
    @WebEndpoint(name = "ConsentimientoConceptoServiceImplPort")
    public ConsentimientoConceptoServiceWs getConsentimientoConceptoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConsentimientoConceptoServiceImplPort"), ConsentimientoConceptoServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CONSENTIMIENTOCONCEPTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
